docs_dir: _build/pydocmd
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - mdx_math
nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting_started.md
  - Documentation:
      - learn2learn: docs/learn2learn.md
  - Examples: https://github.com/seba-1511/learn2learn/tree/master/examples
  - GitHub: https://github.com/seba-1511/learn2learn/
site_dir: _build/site
site_name: learn2learn
theme:
  custom_dir: l2l_theme/
  highlightjs: true
  name: mkdocs
