docs_dir: _build/pydocmd
extra_css: ['https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css']
extra_javascript: ['https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js', 'https://cdn.jsdelivr.net/npm/katex/dist/contrib/mathtex-script-type.min.js']
google_analytics: [UA-68693545-3, seba-1511.github.com]
markdown_extensions: [mdx_math]
nav:
- {Home: index.md}
- Tutorials:
  - {Getting Started: tutorials/getting_started.md}
- Documentation:
  - {learn2learn: docs/learn2learn.md}
- {Examples: 'https://github.com/learnables/learn2learn/tree/master/examples'}
- {GitHub: 'https://github.com/learnables/learn2learn/'}
site_author: Seb Arnold
site_dir: _build/site
site_name: learn2learn
site_url: http://learn2learn.net
theme: {custom_dir: l2l_theme/, highlightjs: true, name: mkdocs}
